2020-03-31 12:53:50 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-03-31 12:53:50 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for circadian_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-03-31 12:53:53 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for huesensor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-03-31 12:53:53 WARNING (MainThread) [homeassistant.components.lovelace] Resources need to be specified in your configuration.yaml. Please see the docs.
2020-03-31 12:53:55 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for wyzesense which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-03-31 12:53:58 ERROR (MainThread) [homeassistant.components.plex] Plex server could not be reached: http://192.168.1.144:32400
2020-03-31 12:53:58 WARNING (MainThread) [hacs] Configuration option 'python_script' is deprecated and you should remove it from your configuration, HACS will know if you use 'python_script' in your Home Assistant configuration, this option will be removed in a future release.
2020-03-31 12:53:58 WARNING (MainThread) [hacs] Configuration option 'theme' is deprecated and you should remove it from your configuration, HACS will know if you use 'theme' in your Home Assistant configuration, this option will be removed in a future release.
2020-03-31 12:54:04 WARNING (MainThread) [homeassistant.components.upnp] Wanted UPnP/IGD device with UDN "uuid:ebf5a0a0-1dd1-11b2-a90f-30230313a61e" not found, aborting
2020-03-31 12:54:09 WARNING (MainThread) [homeassistant.components.template.sensor] Could not render template bathroom_temperature, the state is unknown.
2020-03-31 12:54:09 WARNING (MainThread) [homeassistant.components.template.sensor] Could not render template office_temperature, the state is unknown.
2020-03-31 13:21:37 ERROR (MainThread) [homeassistant.components.automation] Allergy Warning: Error executing script. Service not found for call_service at pos 1: Unable to find service tts/google_translate_say
2020-03-31 13:26:32 ERROR (MainThread) [homeassistant.components.automation] Allergy Warning: Error executing script. Service not found for call_service at pos 1: Unable to find service tts/google_translate_say
2020-03-31 13:29:22 ERROR (SyncWorker_5) [homeassistant.util.yaml.loader] while parsing a block mapping
  in "/mnt/dietpi_userdata/homeassistant/automations/climate.yaml", line 60, column 10
expected <block end>, but found '<scalar>'
  in "/mnt/dietpi_userdata/homeassistant/automations/climate.yaml", line 60, column 66
2020-03-31 13:29:22 ERROR (MainThread) [homeassistant.components.automation] while parsing a block mapping
  in "/mnt/dietpi_userdata/homeassistant/automations/climate.yaml", line 60, column 10
expected <block end>, but found '<scalar>'
  in "/mnt/dietpi_userdata/homeassistant/automations/climate.yaml", line 60, column 66
2020-03-31 13:29:24 ERROR (SyncWorker_0) [homeassistant.util.yaml.loader] while parsing a block mapping
  in "/mnt/dietpi_userdata/homeassistant/automations/climate.yaml", line 60, column 10
expected <block end>, but found '<scalar>'
  in "/mnt/dietpi_userdata/homeassistant/automations/climate.yaml", line 60, column 66
2020-03-31 13:29:51 ERROR (MainThread) [homeassistant.components.automation] Allergy Warning: Error executing script. Service not found for call_service at pos 1: Unable to find service tts/google_translate_say
2020-03-31 13:31:52 ERROR (MainThread) [homeassistant.components.automation] Allergy Warning: Error executing script. Service not found for call_service at pos 1: Unable to find service tts/google_translate_say
